version: 1.0.{build}
os: Visual Studio 2015
install:
- cmd: >-
    set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    dnvm upgrade
build:
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: kDzGILb9iqekj/+T9xB29ODeMJlXdWpZnyYEIZ9dRvzbkL1azmfB0MxXYXnTFwRx
  skip_symbols: false
  artifact: /.*\.nupkg/
