version: 1.0.{build}
os: Visual Studio 2015
install:
- dnvm install 1.0.0-rc1-update2 -r coreclr -arch x86
- dnu restore
build:
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: kDzGILb9iqekj/+T9xB29ODeMJlXdWpZnyYEIZ9dRvzbkL1azmfB0MxXYXnTFwRx
  skip_symbols: false
  artifact: /.*\.nupkg/
