version: 1.0.{build}
os: Visual Studio 2015
install:
- dnvm install 1.0.0-rc1-update2 -r coreclr
- dnvm install 1.0.0-rc1-update2 -r clr
- dnu restore
cache:
  C:\Users\appveyor\.dnx\
build:
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: kDzGILb9iqekj/+T9xB29ODeMJlXdWpZnyYEIZ9dRvzbkL1azmfB0MxXYXnTFwRx
  skip_symbols: false
  artifact: C:\projects\dnxcore-logging-logstash\artifacts\bin\JV.DotNetCore.Extensions.Logging.Logstash\Debug\JV.DotNetCore.Extensions.Logging.Logstash.1.0.0.nupkg
